language: node_js
node_js:
- node
- '6'
- '7'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  slack:
    secure: lZGkRic4eQj7ozqaPh+DVz+04mstUIEPN6djE6/vdU0+zvrEOdIaH4MUNAqVTEMuwGXRHKeHf2Dr26AqCO4ixRiy/EDh8IVlUDp+rlnz299E0MKA98+rRzZ8YhKKxVzMYdXMQ2xOvP5bCnijvMwswXDtGlhvwZMsV8n5TiR006fsqdrqWAjWWzepDDYHcpiNVyKr0o+MhypCfXRsO1ISdsSzvDmNi8YqMH403WhBMIe+yI0rCck1IuOGex1089K4+gadc6Re1cvxkkAQViwBloaH1Z9xJsuATix6ho7LNFcguOMvRW0EsUuwWlFrRnDKokZZxKiOTMuk/2TN60yNCAU7mCZdaMrYtEwYLtrATJzvy3G59jEb8g0c6ijjBRG7LLkHxoRmXB1xaV5FhLb0/pKjaIrozLqigPDidlpjd4t7efbs8sCFefpGTAUFkbTfhuChqB2V1gkWjnPaEd+NHKcLS23AB64ETNUOAsickoEGBubTPix5h5tA20ADzW3U+/u8UU+d6bYTphqrSaZSyIqajuva7Nw9xfFWqnnV2hRy6GzD8t+YckXtgTgnNuonh9BVwRImgqjvkMT/gskcO8dLR9hlIq//H8kRlM/nZhbxefc4ZywUTUI3tdPObYbNqjwVbLHBcwppOiLNXh3W92ZMIkLTbo/OVSSb3KNxKR8=
branches:
  only:
  - master
